### ISSUE TITLE
`hash` vs `hashValue` in Swift 5

### ISSUE THREAD

**Issue by famanson** [OceanLabs/Photobook-iOS#364]
Hi guys, I tried compiling the project in XCode 10.2 and there is a breaking change where `NSObject.hashValue` is now replaced with `NSObject.hash`. This is specifically to do with the `Product` protocol. For now we're using a fork of this project but you might want to fix that moving forward

**Comment by jlandazuri42** [comment]
Thanks for pointing this out Son. Will have a look asap.

**Comment by famanson** [comment]
@jlandazuri42 thanks, I checked just now and saw the new commits. When will it be available on CocoaPods?

**Comment by jlandazuri42** [comment]
I'm in the process of pushing the changes so it should not be long

**Comment by famanson** [comment]
@jlandazuri42 thank you 👍
